apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-pod
  # give different namespace when deploying in production.
  namespace: default
  labels:
    app: rabbit-pod
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: rabbit-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: rabbit-pod
    spec:
      containers:
      - name: rabbit-pod
        # location of your image.
        image: rabbitmq:3-management
        # pass all the environment variables.
        env:
          # You can set the default user and pass for rabbitmq  
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: admin
        # Container needs a volume.
        volumeMounts:
        - name: rabbit-logs
          mountPath: /var/lib/rabbitmq 
      restartPolicy: Always
      volumes:
      # attach the volume to a PVC
      - name: rabbit-logs
        persistentVolumeClaim:
          claimName: rabbit-logs