apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-pod
  # give different namespace when deploying in production.
  namespace: default
  labels:
    app: server-pod
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: server-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: server-pod
    spec:
      containers:
      - name: server-pod
        # location of your image.
        image: hafij/images:rabbit_event_stream_server
        # pass all the environment variables.
        env:
        - name: RABBITMQ_HOST
          value: rabbit
        - name: RABBITMQ_USER
          value: admin
        - name: RABBITMQ_PASS
          value: admin
        # Container needs a volume.
        volumeMounts:
        - name: server-logs
          mountPath: /logs   
      restartPolicy: Always
      volumes:
      # attach the volume to a PVC
      - name: server-logs
        persistentVolumeClaim:
          claimName: server-logs