kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server-logs
  annotations:
    # pvc based on previously created storage class.
    volume.beta.kubernetes.io/storage-class: hafij-storage-class
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
