kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notification-pvc
  annotations:
    # pvc based on previously created storage class.
    volume.beta.kubernetes.io/storage-class: hafij-storage-class
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: hafij-storage-class
  # attach the pvc to a persistent volume
  volumeName: notification-pv
